version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: meka_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
